name: Build on Linux

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt install -y --no-install-recommends gcc g++ yasm nasm python3-venv python3-pip python3-setuptools pkg-config
          python3 -m venv venv
          source venv/bin/activate
          pip3 install wheel
          pip3 install meson
          pip3 install ninja
      - name: configure
        shell: bash
        run: |
          source venv/bin/activate
          bash scripts/reset-submodules.sh
          bash scripts/apply-patches.sh
          bash scripts/build-deps.sh
          cmake -S . -B build
      - name: make
        shell: bash
        run: |
          source venv/bin/activate
          env --chdir build make
